version: "3.8"
services:
  mongo:
    image: mongo:6.0
    ports: ["27017:27017"]
    volumes: ["mongo-data:/data/db"]
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports: ["5000:5000"]
    environment:
      - MONGO_URI=mongodb://mongo:27017/xeno_crm
      - FRONTEND_URL=http://localhost:3000
      - BACKEND_URL=http://localhost:5000
    depends_on: ["mongo"]
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports: ["3000:80"]
    depends_on: ["backend"]
volumes:
  mongo-data:
