FROM node:20-alpine as build
WORKDIR /usr/src/app
COPY frontend/package*.json ./frontend/
WORKDIR /usr/src/app/frontend
RUN npm install
COPY frontend/ .
RUN npm run build
FROM nginx:stable-alpine
COPY --from=build /usr/src/app/frontend/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
