import express from "express";
import cors from "cors";
import dotenv from "dotenv";
import session from "express-session";
import connectDB from "./config/db.js";
import customerRoutes from "./routes/customerRoutes.js";
import orderRoutes from "./routes/orderRoutes.js";
import campaignRoutes from "./routes/campaignRoutes.js";
import deliveryRoutes from "./routes/deliveryRoutes.js";
dotenv.config();
await connectDB();
const app = express();
app.use(cors({ origin: process.env.FRONTEND_URL||"http://localhost:3000", credentials:true }));
app.use(express.json());
app.use(session({ secret: process.env.SESSION_SECRET||"secret", resave:false, saveUninitialized:false }));
app.use("/api/customers", customerRoutes);
app.use("/api/orders", orderRoutes);
app.use("/api/campaigns", campaignRoutes);
app.use("/api/delivery", deliveryRoutes);
app.get("/api/health", (req,res)=>res.json({ ok:true }));
const port = process.env.PORT || 5000;
app.listen(port, ()=> console.log("Backend running on", port));
